
arm0:
  _target_: manimo.actuators.arms.franka_arm.FrankaArm
  arm_cfg:
    robot_ip: "robot2"
    hz: 1000
    action_space: Joint # (Cartesian, Joint)
    delta: True
    ik_mode: DMControl # (DMControl, Polymetis)
    joint_limit_min: [-2.8973, -1.7628, -2.8773, -3.0018, -2.8773, 0.0025, -2.8773]
    joint_limit_max: [2.8773, 1.7428, 2.8773, -0.1398, 2.8773, 3.7325, 2.8773]
    mujoco_xml_path: "${oc.env:MANIMO_PATH}/actuators/arms/models/franka/franka_arm.xml"
    name: "FrankaArm"
    home: [0.0, -0.176076077, 0.0, -1.86691416, 0.0, 1.69344379, 0.0]


    kq: [40, 30, 50, 25, 35, 25, 10]
    kqd: [4, 6, 5, 5, 3, 2, 1]
    kx: [400, 400, 400, 15, 15, 15]
    kxd: [37, 37, 37, 2, 2, 2]
