cam0:
  _target_: manimo.sensors.real_sense_camera.RealSenseCam
  camera_cfg:
    img_width: 640
    img_height: 480
    hz: 30
    name: "cam0"
    device_id: "220422302456" # back, left from person's view
    buffer_size: 1
    window_dur: null  # number of seconds to track in buffer
    warm_start:
      enabled: True
      frames: 60
    intrinsics: [[394.63000488,0.,322.71633911],[0. ,394.63000488, 239.61694336],[0.  ,0.,1.]]
    mv_shift: [-0.0030000000000000027, 1.734723475976807e-18, -2.949029909160572e-17]
    workspace_min: [0.12, -0.7, -0.3]
    workspace_max: [1.0, 0.7, 1.0]

# # this is ZED wrist cam
cam1:
  _target_: manimo.sensors.zed_camera.ZedCam
  cam_cfg:
    img_width: 1280
    img_height: 720
    hz: 15
    name: "cam_wrist"
    device_id: "15034562"
    hcrop: 0
    vcrop: 0
    buffer_size: 1
    window_dur: null  # number of seconds to track in buffer
    warm_start:
      enabled: True
      frames: 60

